# .github/workflows/lint.yml

name: Rust Lint

on:
  push:
    branches: [ main]
      
jobs:
  lint:
    name: Run Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust with Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Run Clippy and annotate PR
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}